spring:
  application:
    name: class8th
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//hi.newlecture.com:1521/XEPDB1
    username: rland
    password: 1128


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html; charset=UTF-8

  encoding:
    charset: UTF-8
    enabled: true
    force: true

  messages:
    basename: messages
    encoding: UTF-8

server:
  port: 8080
# address: ...
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/*Mapper.xml
  type-aliases-package: com.newlecture.web.class8th.entity

logging:
  level:
    com.newlecture.web.class8th.repository: debug
